[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bedrock-agentcore>=1.4.7",
    "bedrock-agentcore-starter-toolkit>=0.2.0",
    "faiss-cpu>=1.13.2",
    "google-adk>=1.14.0",
    "langchain>=1.2.13",
    "langchain-community>=0.4.1",
    "langchain-gemini>=0.1.1",
    "langchain-google-genai>=2.1.10",
    "langchain-groq>=0.3.8",
    "langchain-huggingface>=0.3.1",
    "python-dotenv>=1.1.1",
    "langchain[aws]>=1.1.0",
    "langgraph>=1.0.4",
    "langgraph-checkpoint-aws>=1.0.1",
    "sentence-transformers>=5.1.2",
]
